# Set PREFIX to Ctrl + a
set -g prefix C-a
unbind C-b

# No delay
set -s escape-time 1

# Don't use 0-based index for windows
set -g base-index 1
set-window-option -g pane-base-index 1

# PREFIX + r: reload tmux configuration
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"


# Pass-through PREFIX to underlying application
bind C-a send-prefix


# Split Windows
unbind %
bind \\ split-window -h
unbind '"'
bind - split-window -v

# Navigate though panes using PREFIX + hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r M resize-pane -Z

# Navigate through windows
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
bind C-p previous-window
bind C-n next-window


set-window-option -g monitor-activity on
set -g visual-activity on

# Copy mode
set-window-option -g mode-keys vi


# Colors/statusbar
set -g default-terminal "tmux-256color"

source "~/.dotfiles/config/tmux/catppuccin/catppuccin_frappe.tmux"

