source "$HOME/.dotfiles/config/zsh/global.sh"
source "$HOME/.dotfiles/config/zsh/personal.sh"

# qop
alias qop="/opt/itrp/4me-operations/bin/qop"

# prompt
setopt prompt_subst
PROMPT='$($HOME/.dotfiles/scripts/prompt $?)'

# zoxide
eval "$(zoxide init zsh)"

# asdf
source $(brew --prefix asdf)/libexec/asdf.sh
