. ~/.dotfiles/config/local.zsh
. ~/.dotfiles/config/global.sh
. ~/.dotfiles/config/personal.zsh

powerline-daemon -q
. /usr/local/lib/python2.7/dist-packages/powerline/bindings/zsh/powerline.zsh

DIR="/home/eltaeb/projects/itrp-operations/bin"
alias qop="${DIR}/qop"

# Define the directories you store your projects in in
#   ~/.dotfiles/script/personal.zsh
#
# PROJECT_PARENT_DIRS+=("$HOME/Projects")

# PROJECT_PARENT_DIRS=()

# for PARENT_DIR in ${PROJECT_PARENT_DIRS[@]} ; do
#   if [ -d "$PARENT_DIR" ]; then
#     for PROJECT_DIR in $(/bin/ls $PARENT_DIR); do
#       if [[ ! -z `which $PROJECT_DIR 2> /dev/null` ]]; then
#         if [ -d "$PARENT_DIR/$PROJECT_DIR" ]; then
#           alias "$PROJECT_DIR"="cd $PARENT_DIR/$PROJECT_DIR"
#         fi
#       fi
#     done
#   fi
# done
