source "$HOME/.dotfiles/config/zsh/global.sh"
source "$HOME/.dotfiles/config/zsh/personal.sh"

# qop
alias qop="/opt/itrp/4me-operations/bin/qop"

# prompt
setopt prompt_subst
PROMPT='$($HOME/.dotfiles/scripts/prompt $?)'

# zoxide
eval "$(zoxide init zsh)"

# mysql-client
export PATH="$(brew --prefix mysql-client)/bin:$PATH"
# For compilers to find mysql-client you may need to set:
# export LDFLAGS="-L/opt/homebrew/opt/mysql-client/lib"
# export CPPFLAGS="-I/opt/homebrew/opt/mysql-client/include"

# asdf
source $(brew --prefix asdf)/libexec/asdf.sh
